clusterNodes = [
  { :hostname => "worker-node-2", :ip => "192.168.100.12", :ram => 512, :cpus => 1 },
  { :hostname => "worker-node-1", :ip => "192.168.100.11", :ram => 512, :cpus => 1 },
  { :hostname => "manager-node-1", :ip => "192.168.100.10", :ram => 512, :cpus => 1 }
]

Vagrant.configure("2") do |config|
  clusterNodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "bento/ubuntu-20.04"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.name = node[:ip] + " bento-ubuntu-20.04"
        vb.customize [
          "modifyvm", :id,
          "--memory", node[:ram].to_s,
          "--cpus", node[:cpus].to_s
        ]
      end
    end
  end
  
  config.vm.define "manager-node-1" do |manager|
    manager.vm.network "forwarded_port", guest: 8080, host: 8080
    manager.vm.synced_folder "../../server", "/opt/server"
    manager.vm.provision "file", source: "../Ansible", destination: "$HOME"
    manager.vm.provision "shell", path: "bootstrap.sh"
  end

end