---
- hosts: all
  become: true
  gather_facts: false
  strategy: free

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
        force: yes
    
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest
        force: yes

    - name: Install ca-certificates 
      apt:
        name: ca-certificates
        state: latest
        force: yes

    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: latest
        force: yes
      
    - name: Install curl
      apt:
        name: curl
        state: latest
        force: yes
      
    - name: Install htop
      apt:
        name: htop
        state: latest
        force: yes