---
- hosts: manager-node-1
  become: true

  tasks:
    - name: Install NodeJS
      shell: sudo apt-get install nodejs

    - name: Updating apt-get
      shell: sudo apt-get update

    - name: Install NPM
      shell: sudo apt-get install npm

    - name: Installing PM2
      shell: sudo npm install pm2 -g