---
- hosts: manager-node-1
  become: true

  tasks:
    - name: Install swarm visualizer
      shell: docker run -it -d -p 8080:8080 --restart=always -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer